// alternates/Vue/src/components/Messages.vue
<template>
  <div class="container-item-1">
    <div class="frame-1-1">
      <img class="envelope" :src="envelope" alt="Envelope" />
      <div class="messages poppins-regular-normal-white-12px">
        <span class="poppins-regular-normal-white-12px">{{ spanText }}</span>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Messages",
  props: ["envelope", "spanText"],
};
</script>

<style lang="sass">
.container-item-1
  align-items: center
  border: 1px none
  border-radius: 7px
  display: flex
  height: 44px
  min-width: 158px
  padding: 0 20px

.frame-1-1
  align-items: center
  border: 1px none
  display: flex
  gap: 16px
  min-width: 101px

.envelope,
.circles-four
  height: 24px
  width: 24px

.messages,
.toolboxes
  letter-spacing: 0
  line-height: normal
  margin-bottom: 2.0px
  min-height: 18px
  min-width: 61px
</style>

// components/Messages/index.jsx
import React from "react";
import styled from "styled-components";
import { PoppinsRegularNormalWhite12px } from "../../styledMixins";


function Messages(props) {
  const { envelope, spanText } = props;

  return (
    <Messages1>
      <Frame15>
        <Envelope src={envelope} alt="Envelope" />
        <Messages2>
          <span className="poppins-regular-normal-white-12px">{spanText}</span>
        </Messages2>
      </Frame15>
    </Messages1>
  );
}

const Messages1 = styled.div`
  height: 44px;
  display: flex;
  padding: 0 20px;
  align-items: center;
  min-width: 158px;
  border-radius: 7px;
  border: 1px none;
`;

const Frame15 = styled.div`
  display: flex;
  align-items: center;
  min-width: 101px;
  gap: 16px;
  border: 1px none;
`;

const Envelope = styled.img`
  width: 24px;
  height: 24px;
`;

const Messages2 = styled.div`
  ${PoppinsRegularNormalWhite12px}
  min-height: 18px;
  margin-bottom: 2px;
  min-width: 61px;
  letter-spacing: 0;
`;

export default Messages;
