// alternates/Vue/src/components/Frame12.vue
<template>
  <div class="frame-15">
    <img class="group-2" :src="group2" alt="Group 2" />
    <div class="place-45 poppins-regular-normal-white-12px">
      <span class="poppins-regular-normal-white-12px">{{ spanText }}</span>
    </div>
  </div>
</template>

<script>
export default {
  name: "Frame12",
  props: ["group2", "spanText"],
};
</script>

<style lang="sass">
.frame-15
  align-items: center
  border: 1px none
  display: flex
  gap: 16px
  min-width: 76px

.group-2,
.cloud-check
  height: 24px
  width: 24px

.place-45
  letter-spacing: 0
  line-height: normal
  margin-bottom: 2.0px
  min-height: 18px
  min-width: 36px
</style>

// components/Frame12/index.jsx
import React from "react";
import styled from "styled-components";
import { PoppinsRegularNormalWhite12px } from "../../../styledMixins";


function Frame12(props) {
  const { group2, spanText } = props;

  return (
    <Frame121>
      <Group2 src={group2} alt="Group 2" />
      <Place>
        <span className="poppins-regular-normal-white-12px">{spanText}</span>
      </Place>
    </Frame121>
  );
}

const Frame121 = styled.div`
  display: flex;
  align-items: center;
  min-width: 76px;
  gap: 16px;
  border: 1px none;
`;

const Group2 = styled.img`
  width: 24px;
  height: 24px;
`;

const Place = styled.div`
  ${PoppinsRegularNormalWhite12px}
  min-height: 18px;
  margin-bottom: 2px;
  min-width: 36px;
  letter-spacing: 0;
`;

export default Frame12;
