// alternates/Vue/src/components/User7.vue
<template>
  <div :class="[`user_7 raleway-normal-cape-cod-16px`, className || ``]">
    <img class="ellipse" :src="ellipse2" alt="Ellipse 2" />
    <div class="username_1">username_1</div>
    <div class="githubcom0x0000">github.com/0x0000</div>
  </div>
</template>

<script>
export default {
  name: "User7",
  props: ["ellipse2", "className"],
};
</script>

<style lang="sass">
.user_7
  display: flex
  flex-direction: column
  height: 201px
  left: 1334px
  position: absolute
  top: 0
  width: 154px

.ellipse
  height: 150px
  object-fit: cover
  width: 150px

.username_1
  height: 19px
  letter-spacing: 0
  line-height: normal
  margin-left: 30px
  margin-top: 13px
  width: 90px

.githubcom0x0000
  height: 19px
  letter-spacing: 0
  line-height: normal
  width: 150px

.user_7.user_6,
.user_7.user_6-2,
.user_7.user_6-3,
.user_7.user_6-4,
.user_7.user_6-5,
.user_7.user_6-6,
.user_7.user_6-7,
.user_7.user_6-8,
.user_7.user_6-9,
.user_7.user_6-10,
.user_7.user_6-11
  left: 1184px
  top: 220px

.user_7.user_5,
.user_7.user_5-2,
.user_7.user_5-3,
.user_7.user_5-4,
.user_7.user_5-5,
.user_7.user_5-6,
.user_7.user_5-7,
.user_7.user_5-8,
.user_7.user_5-9,
.user_7.user_5-10,
.user_7.user_5-11
  left: 999px
  top: 70px

.user_7.user_4,
.user_7.user_4-2,
.user_7.user_4-3,
.user_7.user_4-4,
.user_7.user_4-5,
.user_7.user_4-6,
.user_7.user_4-7,
.user_7.user_4-8,
.user_7.user_4-9,
.user_7.user_4-10,
.user_7.user_4-11
  left: 756px
  top: 19px

.user_7.user_3,
.user_7.user_3-2,
.user_7.user_3-3,
.user_7.user_3-4,
.user_7.user_3-5,
.user_7.user_3-6,
.user_7.user_3-7,
.user_7.user_3-8,
.user_7.user_3-9,
.user_7.user_3-10,
.user_7.user_3-11
  left: 476px
  top: 70px

.user_7.user_2,
.user_7.user_2-2,
.user_7.user_2-3,
.user_7.user_2-4,
.user_7.user_2-5,
.user_7.user_2-6,
.user_7.user_2-7,
.user_7.user_2-8,
.user_7.user_2-9,
.user_7.user_2-10,
.user_7.user_2-11
  left: 253px
  top: 220px

.user_7.user_1,
.user_7.user_1-1,
.user_7.user_1-2,
.user_7.user_1-3,
.user_7.user_1-4,
.user_7.user_1-5,
.user_7.user_1-6,
.user_7.user_1-7,
.user_7.user_1-8,
.user_7.user_1-9,
.user_7.user_1-10
  left: 25px
  top: 349px

.user_7.user-2
  align-self: flex-end
  left: unset
  position: unset
  top: unset

.user_7.user_2-1
  align-self: center
  left: unset
  margin-left: 74px
  margin-top: 91.0px
  position: unset
  top: unset

.user_7.user_3-1
  left: unset
  margin-left: 69px
  margin-top: 70px
  position: unset
  top: unset

.user_7.user_4-1
  left: unset
  margin-left: 126px
  margin-top: 19px
  position: unset
  top: unset

.user_7.user_5-1
  left: unset
  margin-left: 89px
  margin-top: 70px
  position: unset
  top: unset

.user_7.user_6-1
  left: unset
  position: unset
  top: unset
</style>

// cleanfolio-anima/components/User7/index.jsx
import React from "react";
import styled from "styled-components";
import { RalewayNormalCapeCod16px } from "../../styledMixins";


function User7(props) {
  const { ellipse2, className } = props;

  return (
    <User71 className={`user_7 ${className || ""}`}>
      <Ellipse2 className="ellipse-2" src={ellipse2} alt="Ellipse 2" />
      <Username1 className="username_1">
        <span className="spanq7yei raleway-normal-cape-cod-16px">username_1</span>
      </Username1>
      <Githubcom0x0000 className="githubcom0x0000">
        <span className="spancmlz8 raleway-normal-cape-cod-16px">github.com/0x0000</span>
      </Githubcom0x0000>
    </User71>
  );
}

const User71 = styled.div`
  ${RalewayNormalCapeCod16px}
  position: absolute;
  width: 154px;
  top: 0;
  left: 1334px;
  display: flex;
  flex-direction: column;
  align-items: center;
  min-height: 201px;

  &.user_7.user_6 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_6-1 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-1 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-1 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-1 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-1 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-1 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_6-2 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-2 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-2 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-2 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-2 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-2 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_6-3 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-3 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-3 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-3 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-3 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-3 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_6-4 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-4 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-4 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-4 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-4 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-4 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_6-5 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-5 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-5 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-5 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-5 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-5 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_6-6 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-6 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-6 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-6 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-6 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-6 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_1-7 {
    align-self: flex-end;
    position: unset;
    top: unset;
    left: unset;
  }

  &.user_7.user_2-7 {
    align-self: center;
    margin-left: 74px;
    margin-top: 91px;
    position: unset;
    top: unset;
    left: unset;
  }

  &.user_7.user_3-7 {
    margin-left: 69px;
    margin-top: 70px;
    position: unset;
    top: unset;
    left: unset;
  }

  &.user_7.user_4-7 {
    margin-left: 126px;
    margin-top: 19px;
    position: unset;
    top: unset;
    left: unset;
  }

  &.user_7.user_5-7 {
    margin-left: 89px;
    margin-top: 70px;
    position: unset;
    top: unset;
    left: unset;
  }

  &.user_7.user_7-7 {
    align-self: flex-end;
    position: unset;
    top: unset;
    left: unset;
  }

  &.user_7.user_6-7 {
    position: unset;
    top: unset;
    left: unset;
  }

  &.user_7.user_6-8 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-8 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-8 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-8 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-8 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-8 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_6-9 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-9 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-9 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-9 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-9 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-9 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_6-10 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-10 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-10 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-10 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-10 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-10 {
    top: 349px;
    left: 25px;
  }

  &.user_7.user_6-11 {
    top: 220px;
    left: 1184px;
  }

  &.user_7.user_5-11 {
    top: 70px;
    left: 999px;
  }

  &.user_7.user_4-11 {
    top: 19px;
    left: 756px;
  }

  &.user_7.user_3-11 {
    top: 70px;
    left: 476px;
  }

  &.user_7.user_2-11 {
    top: 220px;
    left: 253px;
  }

  &.user_7.user_1-11 {
    top: 349px;
    left: 25px;
  }
`;

const Ellipse2 = styled.img`
  width: 150px;
  height: 150px;
  margin-right: 4px;
  object-fit: cover;
`;

const Username1 = styled.div`
  min-height: 19px;
  margin-top: 12px;
  margin-right: 4px;
  min-width: 90px;
  letter-spacing: 0;
`;

const Githubcom0x0000 = styled.div`
  min-height: 19px;
  margin-right: 4px;
  min-width: 150px;
  letter-spacing: 0;
`;

export default User7;
