// alternates/Vue/src/components/Group23.vue
<template>
  <div :class="[`group-23`, className || ``]">
    <div class="number-2 poppins-regular-normal-mountain-mist-12px">
      <span class="span-24 poppins-regular-normal-mountain-mist-12px">{{ spanText }}</span>
    </div>
    <img
      class="line-1-31"
      src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/6338ef14129a3c9f74314c25/img/line-12-2@2x.png"
      alt="Line 12"
    />
  </div>
</template>

<script>
export default {
  name: "Group23",
  props: ["spanText", "className"],
};
</script>

<style lang="sass">
.group-23
  align-items: flex-start
  display: flex
  gap: 16px
  height: 18px
  min-width: 309px

.number-2
  letter-spacing: 0
  line-height: normal
  margin-top: -1px
  text-align: center
  width: 28px

.line-1-31
  align-self: center
  height: 1px
  margin-bottom: 2.0px
  width: 263px

.group-23.group-24
  margin-left: 1px

.group-23.group-25
  margin-left: 2px
</style>

// components/Group23/index.jsx
import React from "react";
import styled from "styled-components";
import { PoppinsRegularNormalMountainMist12p } from "../../styledMixins";


function Group23(props) {
  const { spanText, className } = props;

  return (
    <Group231 className={`group-23 ${className || ""}`}>
      <Number className="number-2">
        <span className="spankm0zw poppins-regular-normal-mountain-mist-12px">{spanText}</span>
      </Number>
      <Line12 className="line-12" src="/img/line-12-2@2x.png" alt="Line 12" />
    </Group231>
  );
}

const Group231 = styled.div`
  height: 18px;
  display: flex;
  align-items: flex-start;
  min-width: 309px;
  gap: 16px;

  &.group-23.group-24 {
    margin-left: 1px;
  }

  &.group-23.group-25 {
    margin-left: 2px;
  }
`;

const Number = styled.div`
  ${PoppinsRegularNormalMountainMist12p}
  width: 28px;
  min-height: 18px;
  margin-top: -1px;
  text-align: center;
  letter-spacing: 0;
`;

const Line12 = styled.img`
  width: 263px;
  height: 1px;
  align-self: center;
  margin-bottom: 2px;
`;

export default Group23;
