// alternates/Vue/src/components/TS.vue
<template>
  <div class="ts screen">
    <div class="ts-1">
      <div class="body-29">
        <navbar7
          :className="navbar7Props.className"
          :buttonLoginProps="navbar7Props.buttonLoginProps"
          :buttonWalletProps="navbar7Props.buttonWalletProps"
        />
        <div class="hero-25">
          <div class="flex-col-17">
            <div class="terra-solstice raleway-normal-cape-cod-100px">{{ terrasolstice }}</div>
            <p class="this-web-30-applica-7 raleway-normal-cape-cod-26px">{{ thisWeb30Applica }}</p>
            <div class="flex-row-96">
              <div class="overlap-group-94">
                <div class="contribute-7 raleway-bold-white-32px">{{ contribute }}</div>
              </div>
              <button215 :dashboard="button215Props.dashboard" />
            </div>
          </div>
          <img class="terrasolstice-logo-1" :src="terrasolsticeLogo11" alt="terrasolstice-logo 1" />
        </div>
        <products :className="productsProps.className" :downloadsProps="productsProps.downloadsProps" />
        <tools
          :className="toolsProps.className"
          :packages1Props="toolsProps.packages1Props"
          :packages2Props="toolsProps.packages2Props"
          :packages3Props="toolsProps.packages3Props"
        />
        <div class="team-7">
          <div class="become-a-contributor-7 raleway-normal-white-100px">
            <span class="raleway-normal-cape-cod-100px">{{ spanText1 }}</span
            ><span class="span1-13">{{ spanText2 }}</span>
          </div>
          <avatars
            :user71Props="avatarsProps.user71Props"
            :user72Props="avatarsProps.user72Props"
            :user73Props="avatarsProps.user73Props"
            :user74Props="avatarsProps.user74Props"
            :user75Props="avatarsProps.user75Props"
            :user76Props="avatarsProps.user76Props"
            :user77Props="avatarsProps.user77Props"
          />
        </div>
        <div class="live-developing-7">
          <dev-environment :className="devEnvironmentProps.className" />
          <div class="flex-row-97">
            <div class="overlap-group-95">
              <div class="learn-how-7 valign-text-middle raleway-bold-white-32px">{{ learnHow }}</div>
            </div>
            <button216 :dashboard="button216Props.dashboard" />
          </div>
        </div>
        <div class="footer-39">
          <div class="footer-menu-27">
            <img class="terrasolstice-logo-1-1" :src="terrasolsticeLogo12" alt="terrasolstice-logo 1" />
            <div class="flex-row-98 raleway-bold-cape-cod-20px">
              <div class="hire-me-59">{{ hireMe }}</div>
              <div class="github-46">{{ github }}</div>
              <div class="open-source-58">{{ openSource }}</div>
              <div class="organizations-48">{{ organizations }}</div>
              <img class="button-53" :src="button1" alt="button" /><img class="button-54" :src="button2" alt="button" />
            </div>
          </div>
          <div class="flex-row-99">
            <img class="image-8-26" :src="image8" alt="image 8" />
            <div class="overlap-group-96">
              <div class="snippet-of-the-day-34 valign-text-middle raleway-bold-white-36px">{{ snippetOfTheDay }}</div>
              <div class="flex-row-100">
                <div class="subscribe-to-get-access-34 valign-text-middle raleway-bold-white-20px">
                  {{ subscribeToGetAccess }}
                </div>
                <div class="rectangle-6-26"></div>
                <div class="rectangle-7-27"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Navbar7 from "./Navbar7";
import Button215 from "./Button215";
import Products from "./Products";
import Tools from "./Tools";
import Avatars from "./Avatars";
import DevEnvironment from "./DevEnvironment";
import Button216 from "./Button216";
export default {
  name: "TS",
  components: {
    Navbar7,
    Button215,
    Products,
    Tools,
    Avatars,
    DevEnvironment,
    Button216,
  },
  props: [
    "terrasolstice",
    "thisWeb30Applica",
    "contribute",
    "terrasolsticeLogo11",
    "spanText1",
    "spanText2",
    "learnHow",
    "terrasolsticeLogo12",
    "hireMe",
    "github",
    "openSource",
    "organizations",
    "button1",
    "button2",
    "image8",
    "snippetOfTheDay",
    "subscribeToGetAccess",
    "navbar7Props",
    "button215Props",
    "productsProps",
    "toolsProps",
    "avatarsProps",
    "devEnvironmentProps",
    "button216Props",
  ],
};
</script>

<style lang="sass">
@import '../../variables'

.ts
  align-items: center
  border: 1px none
  display: flex
  flex-direction: column
  gap: 122px
  height: 100vh
  min-height: 5592px
  min-width: 1512px
  width: 100%

.ts-1
  display: flex
  height: 5592px
  min-width: 1512px

.body-29
  background-color: $material-themereferrorerror100
  border: 1px none
  display: flex
  flex-direction: column
  height: 5592px
  position: relative
  width: 1512px

.hero-25
  align-items: center
  background-color: $material-themereferrorerror100
  border: 1px none
  display: flex
  gap: 172px
  width: 1512px

.flex-col-17
  align-items: flex-start
  display: flex
  flex-direction: column
  margin-bottom: 116.0px
  margin-left: 97px
  min-height: 394px
  width: 598px

.terra-solstice
  letter-spacing: 0
  line-height: normal
  min-height: 117px

.this-web-30-applica-7
  letter-spacing: 0
  line-height: normal
  margin-top: 44px
  width: 570px

.flex-row-96
  align-items: flex-start
  display: flex
  gap: 25px
  margin-top: 72px
  min-width: 539px
  position: relative

.overlap-group-94
  align-items: center
  background-color: $yellow-sunshine
  border-radius: 16px
  display: flex
  height: 68px
  justify-content: flex-end
  min-width: 257px
  padding: 0 25px

.contribute-7
  letter-spacing: 0
  line-height: normal
  min-height: 38px
  min-width: 206px

.terrasolstice-logo-1
  height: 982px
  object-fit: cover
  width: 645px

.team-7
  background-color: $material-themereferrorerror100
  border: 1px none
  display: flex
  flex-direction: column
  gap: 60px
  height: 982px
  position: relative

.become-a-contributor-7
  height: 117px
  letter-spacing: 0
  line-height: normal
  margin-left: 253px
  margin-top: 105px
  width: 1006px

.span1-13
  color: $yellow-sunshine
  font-family: $font-family-raleway
  font-size: $font-size-xxxl
  font-weight: 400

.live-developing-7
  align-items: center
  background-color: $material-themereferrorerror100
  border: 1px none
  display: flex
  flex-direction: column
  gap: 66px
  height: 982px
  padding: 40px 0
  position: relative

.flex-row-97
  align-items: flex-start
  display: flex
  gap: 100px
  min-width: 614px
  position: relative

.overlap-group-95
  align-items: center
  background-color: $yellow-sunshine
  border-radius: 16px
  display: flex
  height: 68px
  min-width: 257px
  padding: 0 26px

.learn-how-7
  height: 38px
  letter-spacing: 0
  line-height: normal
  min-width: 194px
  text-align: center

.footer-39
  align-items: flex-end
  background-color: $material-themereferrorerror100
  border: 1px none
  display: flex
  flex-direction: column
  gap: 33px
  height: 592px
  padding: 54px 27.1px

.footer-menu-27
  align-items: center
  display: flex
  flex-direction: column
  gap: 38px
  margin-top: 3px
  min-height: 223px
  width: 1391px

.terrasolstice-logo-1-1
  height: 125px
  margin-right: 67.85px
  object-fit: cover
  width: 125px

.flex-row-98
  align-items: center
  display: flex
  margin-right: 8.0px
  min-width: 1383px

.hire-me-59
  letter-spacing: 0
  line-height: normal
  margin-top: 1.0px
  text-align: center
  width: 124px

.github-46
  letter-spacing: 0
  line-height: normal
  margin-left: 30px
  margin-top: 1.0px
  text-align: center
  width: 118px

.open-source-58
  letter-spacing: 0
  line-height: normal
  margin-bottom: 1.0px
  margin-left: 28px
  text-align: center
  width: 223px

.organizations-48
  letter-spacing: 0
  line-height: normal
  margin-left: 29px
  margin-top: 1.0px
  text-align: center
  width: 250px

.button-53
  height: 60px
  margin-left: 76px
  width: 215px

.button-54
  height: 60px
  margin-left: 75px
  width: 215px

.flex-row-99
  align-items: flex-end
  display: flex
  gap: 100px
  margin-right: 7.85px
  min-width: 1403px

.image-8-26
  height: 225px
  object-fit: cover
  width: 640px

.overlap-group-96
  align-items: flex-start
  background-color: $yellow-sunshine
  border-radius: 16px
  display: flex
  flex-direction: column
  gap: 21px
  min-height: 164px
  padding: 19px 14px
  width: 663px

.snippet-of-the-day-34
  align-self: center
  height: 51px
  letter-spacing: 0
  line-height: normal
  margin-left: 1.54px
  text-align: center
  width: 367px

.flex-row-100
  align-items: flex-end
  display: flex
  gap: 18px
  min-width: 620px

.subscribe-to-get-access-34
  align-self: flex-start
  height: 49px
  letter-spacing: 0
  line-height: normal
  text-align: center
  width: 167px

.rectangle-6-26
  background-color: $material-themereferrorerror100
  border: 1px none
  border-radius: 16px
  height: 33px
  width: 316px

.rectangle-7-27
  background-color: $white
  border: 1px none
  border-radius: 16px
  height: 33px
  width: 101px
</style>

// cleanfolio-anima/components/TS/index.jsx
import React from "react";
import Navbar3 from "../Navbar3";
import Products from "../Products";
import Tools from "../Tools";
import User7 from "../User7";
import DevEnvironment from "../DevEnvironment";
import styled from "styled-components";
import {
  RalewayBoldWhite36px,
  RalewayBoldCapeCod20px,
  RalewayBoldWhite20px,
  RalewayBoldYellowSunshine32px,
  RalewayNormalCapeCod100px,
  RalewayBoldWhite32px,
  RalewayNormalCapeCod26px,
  ValignTextMiddle,
} from "../../styledMixins";
import "./TS.css";

function TS(props) {
  const {
    spanText1,
    spanText2,
    spanText3,
    spanText4,
    terrasolsticeLogo11,
    spanText5,
    spanText6,
    spanText7,
    spanText8,
    terrasolsticeLogo12,
    spanText9,
    spanText10,
    spanText11,
    spanText12,
    button1,
    button2,
    image8,
    spanText13,
    spanText14,
    navbarProps,
    productsProps,
    toolsProps,
    user71Props,
    user72Props,
    user73Props,
    user74Props,
    user75Props,
    user76Props,
    user77Props,
  } = props;

  return (
    <div className="container-center-horizontal">
      <div className="ts screen">
        <Body>
          <Navbar3 {...navbarProps} />
          <Hero>
            <FlexCol>
              <TerraSolstice>
                <span className="raleway-normal-cape-cod-100px">{spanText1}</span>
              </TerraSolstice>
              <ThisWeb30Applica>
                <span className="raleway-normal-cape-cod-26px">{spanText2}</span>
              </ThisWeb30Applica>
              <FlexRow>
                <OverlapGroup>
                  <CONTRIBUTE>
                    <span className="raleway-bold-white-32px">{spanText3}</span>
                  </CONTRIBUTE>
                </OverlapGroup>
                <Button2>
                  <DASHBOARD>
                    <span className="raleway-bold-yellow-sunshine-32px">{spanText4}</span>
                  </DASHBOARD>
                </Button2>
              </FlexRow>
            </FlexCol>
            <TerrasolsticeLogo1 src={terrasolsticeLogo11} alt="terrasolstice-logo 1" />
          </Hero>
          <Products className={productsProps.className} downloadsProps={productsProps.downloadsProps} />
          <Tools className={toolsProps.className} />
          <Team>
            <BecomeAContributor>
              <span className="raleway-normal-cape-cod-100px">{spanText5}</span>
              <Span116>{spanText6}</Span116>
            </BecomeAContributor>
            <OverlapGroup1>
              <Vector src="/img/vector-20@2x.png" alt="Vector" />
              <User7 ellipse2={user71Props.ellipse2} />
              <User7 ellipse2={user72Props.ellipse2} className={user72Props.className} />
              <User7 ellipse2={user73Props.ellipse2} className={user73Props.className} />
              <User7 ellipse2={user74Props.ellipse2} className={user74Props.className} />
              <User7 ellipse2={user75Props.ellipse2} className={user75Props.className} />
              <User7 ellipse2={user76Props.ellipse2} className={user76Props.className} />
              <User7 ellipse2={user77Props.ellipse2} className={user77Props.className} />
            </OverlapGroup1>
          </Team>
          <LiveDeveloping>
            <DevEnvironment />
            <FlexRow1>
              <OverlapGroup2>
                <LEARNHOW>
                  <span>
                    <span className="raleway-bold-white-32px">{spanText7}</span>
                  </span>
                </LEARNHOW>
              </OverlapGroup2>
              <Button21>
                <DASHBOARD1>
                  <span>
                    <span className="raleway-bold-yellow-sunshine-32px">{spanText8}</span>
                  </span>
                </DASHBOARD1>
              </Button21>
            </FlexRow1>
          </LiveDeveloping>
          <Footer>
            <FooterMenu>
              <TerrasolsticeLogo11 src={terrasolsticeLogo12} alt="terrasolstice-logo 1" />
              <FlexRow2>
                <HIREME>
                  <span className="raleway-bold-cape-cod-20px">{spanText9}</span>
                </HIREME>
                <GITHUB>
                  <span className="raleway-bold-cape-cod-20px">{spanText10}</span>
                </GITHUB>
                <OPENSOURCE>
                  <span className="raleway-bold-cape-cod-20px">{spanText11}</span>
                </OPENSOURCE>
                <ORGANIZATIONS>
                  <span className="raleway-bold-cape-cod-20px">{spanText12}</span>
                </ORGANIZATIONS>
                <Button src={button1} alt="button" />
                <Button1 src={button2} alt="button" />
              </FlexRow2>
            </FooterMenu>
            <FlexRow3>
              <Image8 src={image8} alt="image 8" />
              <OverlapGroup3>
                <SnippetOfTheDay>
                  <span>
                    <span className="raleway-bold-white-36px">{spanText13}</span>
                  </span>
                </SnippetOfTheDay>
                <FlexRow4>
                  <SubscribeToGetAccess>
                    <span>
                      <span className="raleway-bold-white-20px">{spanText14}</span>
                    </span>
                  </SubscribeToGetAccess>
                  <Rectangle6></Rectangle6>
                  <Rectangle7></Rectangle7>
                </FlexRow4>
              </OverlapGroup3>
            </FlexRow3>
          </Footer>
        </Body>
      </div>
    </div>
  );
}

const Body = styled.div`
  width: 1512px;
  height: 5592px;
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  background-color: var(--material-themereferrorerror100);
  border: 1px none;
`;

const Hero = styled.div`
  width: 1512px;
  height: 982px;
  display: flex;
  align-items: flex-start;
  gap: 172px;
  background-color: var(--material-themereferrorerror100);
  overflow: hidden;
  border: 1px none;
`;

const FlexCol = styled.div`
  width: 598px;
  align-self: center;
  margin-left: 97px;
  margin-bottom: 116px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  min-height: 394px;
`;

const TerraSolstice = styled.div`
  ${RalewayNormalCapeCod100px}
  min-height: 117px;
  letter-spacing: 0;
`;

const ThisWeb30Applica = styled.div`
  ${RalewayNormalCapeCod26px}
  width: 570px;
  min-height: 93px;
  margin-top: 44px;
  letter-spacing: 0;
`;

const FlexRow = styled.div`
  margin-top: 72px;
  display: flex;
  align-items: flex-start;
  min-width: 539px;
  gap: 25px;
`;

const OverlapGroup = styled.div`
  height: 68px;
  display: flex;
  padding: 14px 25px;
  justify-content: flex-end;
  align-items: flex-start;
  min-width: 257px;
  background-color: var(--yellow-sunshine);
  border-radius: 16px;
`;

const CONTRIBUTE = styled.div`
  ${RalewayBoldWhite32px}
  min-height: 38px;
  letter-spacing: 0;
`;

const DASHBOARD = styled.div`
  ${RalewayBoldYellowSunshine32px}
  min-height: 38px;
  letter-spacing: 0;
`;

const Button2 = styled.div`
  height: 68px;
  display: flex;
  padding: 14px 26px;
  align-items: flex-start;
  min-width: 257px;
  background-color: var(--material-themereferrorerror100);
  border-radius: 16px;
  border: 1px none;
  box-shadow: 0px 4px 4px #fcf50040;
`;

const TerrasolsticeLogo1 = styled.img`
  width: 1040px;
  height: 1040px;
  margin-top: -20px;
  object-fit: cover;
`;

const Team = styled.div`
  width: 1512px;
  height: 982px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 61px;
  background-color: var(--material-themereferrorerror100);
  border: 1px none;
`;

const BecomeAContributor = styled.div`
  ${RalewayNormalCapeCod100px}
  min-height: 117px;
  margin-top: 104px;
  min-width: 1006px;
  letter-spacing: 0;
`;

const Span116 = styled.span`
  font-family: var(--font-family-raleway);
  font-weight: 400;
  color: var(--yellow-sunshine);
  font-size: 100px;
`;

const OverlapGroup1 = styled.div`
  width: 1512px;
  height: 700px;
  position: relative;
`;

const Vector = styled.img`
  position: absolute;
  width: 1512px;
  height: 500px;
  top: 200px;
  left: 0;
`;

const LiveDeveloping = styled.div`
  width: 1512px;
  height: 982px;
  position: relative;
  display: flex;
  flex-direction: column;
  padding: 40px 0;
  align-items: center;
  gap: 66px;
  background-color: var(--material-themereferrorerror100);
  border: 1px none;
`;

const FlexRow1 = styled.div`
  display: flex;
  align-items: flex-start;
  min-width: 614px;
  gap: 100px;
`;

const OverlapGroup2 = styled.div`
  height: 68px;
  display: flex;
  padding: 14px 26px;
  align-items: flex-start;
  min-width: 257px;
  background-color: var(--yellow-sunshine);
  border-radius: 16px;
`;

const LEARNHOW = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite32px}
            height: 38px;
  min-width: 194px;
  text-align: center;
  letter-spacing: 0;
`;

const Button21 = styled.div`
  height: 68px;
  display: flex;
  padding: 14px 31px;
  align-items: flex-start;
  min-width: 257px;
  background-color: var(--material-themereferrorerror100);
  border-radius: 16px;
  border: 1px none;
  box-shadow: 0px 4px 4px #00000040;
`;

const DASHBOARD1 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldYellowSunshine32px}
            height: 38px;
  min-width: 189px;
  text-align: center;
  letter-spacing: 0;
`;

const Footer = styled.div`
  width: 1512px;
  height: 592px;
  display: flex;
  flex-direction: column;
  padding: 54px 27.1px;
  align-items: flex-end;
  gap: 33px;
  background-color: var(--material-themereferrorerror100);
  border: 1px none;
`;

const FooterMenu = styled.div`
  width: 1391px;
  margin-top: 3px;
  display: flex;
  flex-direction: column;
  align-items: center;
  min-height: 223px;
  gap: 38px;
`;

const TerrasolsticeLogo11 = styled.img`
  width: 125px;
  height: 125px;
  margin-right: 67.85px;
  object-fit: cover;
`;

const FlexRow2 = styled.div`
  ${RalewayBoldCapeCod20px}
  margin-right: 8.0px;
  display: flex;
  align-items: center;
  min-width: 1383px;
`;

const HIREME = styled.div`
  width: 124px;
  min-height: 23px;
  margin-bottom: 1px;
  text-align: center;
  letter-spacing: 0;
`;

const GITHUB = styled.div`
  width: 118px;
  min-height: 23px;
  margin-left: 30px;
  margin-bottom: 1px;
  text-align: center;
  letter-spacing: 0;
`;

const OPENSOURCE = styled.div`
  width: 223px;
  min-height: 23px;
  margin-left: 28px;
  margin-bottom: 3px;
  text-align: center;
  letter-spacing: 0;
`;

const ORGANIZATIONS = styled.div`
  width: 250px;
  min-height: 23px;
  margin-left: 29px;
  margin-bottom: 1px;
  text-align: center;
  letter-spacing: 0;
`;

const Button = styled.img`
  width: 215px;
  height: 60px;
  margin-left: 76px;
`;

const Button1 = styled.img`
  width: 215px;
  height: 60px;
  margin-left: 75px;
`;

const FlexRow3 = styled.div`
  margin-right: 7.85px;
  display: flex;
  align-items: flex-end;
  min-width: 1403px;
  gap: 100px;
`;

const Image8 = styled.img`
  width: 640px;
  height: 225px;
  object-fit: cover;
`;

const OverlapGroup3 = styled.div`
  width: 663px;
  display: flex;
  flex-direction: column;
  padding: 18px 14px;
  align-items: flex-start;
  min-height: 164px;
  gap: 21px;
  background-color: var(--yellow-sunshine);
  border-radius: 16px;
`;

const SnippetOfTheDay = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            width: 367px;
  height: 51px;
  align-self: center;
  margin-left: 1.54px;
  text-align: center;
  letter-spacing: 0;
`;

const FlexRow4 = styled.div`
  height: 50px;
  display: flex;
  align-items: flex-end;
  min-width: 620px;
  gap: 18px;
`;

const SubscribeToGetAccess = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite20px}
            width: 167px;
  height: 49px;
  align-self: flex-start;
  text-align: center;
  letter-spacing: 0;
`;

const Rectangle6 = styled.div`
  width: 316px;
  height: 33px;
  background-color: var(--material-themereferrorerror100);
  border-radius: 16px;
  border: 1px none;
`;

const Rectangle7 = styled.div`
  width: 101px;
  height: 33px;
  background-color: var(--white);
  border-radius: 16px;
  border: 1px none;
`;

export default TS;
