// alternates/Vue/src/components/Button22.vue
<template>
  <div class="button-2-2">
    <div class="dashboard-1 valign-text-middle raleway-bold-mexican-red-32px">{{ dashboard }}</div>
  </div>
</template>

<script>
export default {
  name: "Button22",
  props: ["dashboard"],
};
</script>

<style lang="sass">
@import '../../variables'

.button-2-2
  align-items: flex-start
  background-color: $material-themereferrorerror100
  border: 1px none
  border-radius: 16px
  box-shadow: 0px 4px 4px #00000040
  display: flex
  height: 68px
  min-width: 257px
  padding: 14px 31px

.dashboard-1
  height: 38px
  letter-spacing: 0
  line-height: normal
  min-width: 189px
  text-align: center
</style>

// components/Button22/index.jsx
import React from "react";
import "./Button22.css";

function Button22(props) {
  const { children } = props;

  return (
    <div className="button-2-2">
      <div className="dashboard-2 valign-text-middle raleway-bold-mexican-red-32px">{children}</div>
    </div>
  );
}

export default Button22;
