// alternates/Vue/src/components/DevEnvironment.vue
<template>
  <div :class="[`dev-environment`, className || ``]">
    <div class="duckly">
      <div class="duckly-environment valign-text-middle raleway-bold-white-36px">Duckly Environment</div>
      <img
        class="flying-duck"
        src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/flying-duck@2x.png"
        alt="Flying Duck"
      />
    </div>
  </div>
</template>

<script>
export default {
  name: "DevEnvironment",
  props: ["className"],
};
</script>

<style lang="sass">
.dev-environment
  background-image: url(https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/-livestream@1x.svg)
  background-size: 100% 100%
  display: flex
  height: 720px
  width: 1200px

.duckly
  display: flex
  flex-direction: column
  gap: 32px
  height: 170px
  margin-left: 426px
  margin-top: 266px
  width: 349px

.duckly-environment
  height: 42px
  letter-spacing: 0
  line-height: normal
  text-align: center
  width: 347px

.flying-duck
  height: 96px
  margin-left: 126px
  width: 96px

.dev-environment.dev-environment-1
  background-image: url(https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/-livestream-1@1x.svg)

.dev-environment.dev-environment-2
  background-image: url(https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/-livestream-2@1x.svg)

.dev-environment.dev-environment-3,
.dev-environment.dev-environment-4,
.dev-environment.dev-environment-5,
.dev-environment.dev-environment-6,
.dev-environment.dev-environment-7,
.dev-environment.dev-environment-8,
.dev-environment.dev-environment-9,
.dev-environment.dev-environment-10,
.dev-environment.dev-environment-11
  background-image: url(https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/63448a608ca1456239ecb8bf/img/-livestream@1x.png)
</style>

// cleanfolio-anima/components/DevEnvironment/index.jsx
import React from "react";
import styled from "styled-components";
import { RalewayBoldWhite36px, ValignTextMiddle } from "../../../styledMixins";


function DevEnvironment() {
  return (
    <DevEnvironment1>
      <DucklyEnvironment>
        <span>
          <span className="raleway-bold-white-36px">Duckly Environment</span>
        </span>
      </DucklyEnvironment>
      <FlyingDuck src="/img/flying-duck-10@2x.png" alt="Flying Duck" />
    </DevEnvironment1>
  );
}

const DevEnvironment1 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment2 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment1 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck1 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment3 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment2 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck2 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment4 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment3 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck3 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment5 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment4 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck4 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment6 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment5 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck5 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment7 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment6 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck6 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment8 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment7 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck7 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment9 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment8 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck8 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment10 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment9 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck9 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment11 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment10 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck10 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

const DevEnvironment12 = styled.div`
  width: 1200px;
  display: flex;
  flex-direction: column;
  padding: 265px 426px;
  align-items: flex-start;
  min-height: 720px;
  gap: 33px;
  background-image: url(/img/-livestream-12@2x.png);
  background-size: 100% 100%;
`;

const DucklyEnvironment11 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite36px}
            height: 42px;
  min-width: 347px;
  text-align: center;
  letter-spacing: 0;
`;

const FlyingDuck11 = styled.img`
  width: 96px;
  height: 96px;
  align-self: center;
`;

export default DevEnvironment;
