// alternates/Vue/src/components/Ethereum.vue
<template>
  <div :class="[`ethereum-5`, className || ``]">
    <img
      class="ethereum-6"
      src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634ef8f1abca668fdefc42a0/img/ethereum@2x.png"
      alt="Ethereum"
    />
    <div class="ethereum-7 inter-bold-cape-cod-22px">Ethereum</div>
  </div>
</template>

<script>
export default {
  name: "Ethereum",
  props: ["className"],
};
</script>

<style lang="sass">
.ethereum-5,
.ethereum-5.ethereum,
.ethereum-5.ethereum-12,
.ethereum-5.ethereum-15,
.ethereum-5.ethereum-18,
.ethereum-5.ethereum-20,
.ethereum-5.ethereum-21,
.ethereum-5.ethereum-22,
.ethereum-5.ethereum-23,
.ethereum-5.ethereum-24,
.ethereum-5.ethereum-25,
.ethereum-5.ethereum-26,
.ethereum-5.ethereum-27,
.ethereum-5.ethereum-28,
.ethereum-5.ethereum-29,
.ethereum-5.ethereum-3
  display: flex
  gap: 17.8px
  width: 197.61px

.ethereum-6
  height: 45px
  margin-left: 0
  width: 53.35px

.ethereum-7
  height: 27px
  letter-spacing: 0
  line-height: normal
  margin-top: 9px
  width: 124.48px

.ethereum-5.ethereum-11 .ethereum-6,
.ethereum-5.ethereum-17 .ethereum-6,
.ethereum-5.ethereum-12 .ethereum-6,
.ethereum-5.ethereum-3 .ethereum-6
  width: 53.35px

.ethereum-5.ethereum-14 .ethereum-6,
.ethereum-5.ethereum-15 .ethereum-6
  width: 53.35px

.ethereum-5.ethereum-20 .ethereum-6,
.ethereum-5.ethereum-21 .ethereum-6,
.ethereum-5.ethereum-22 .ethereum-6,
.ethereum-5.ethereum-23 .ethereum-6,
.ethereum-5.ethereum-24 .ethereum-6,
.ethereum-5.ethereum-25 .ethereum-6,
.ethereum-5.ethereum-26 .ethereum-6,
.ethereum-5.ethereum-27 .ethereum-6,
.ethereum-5.ethereum-28 .ethereum-6,
.ethereum-5.ethereum-29 .ethereum-6,
.ethereum-5.ethereum .ethereum-6
  width: 53.35px
</style>

// components/Ethereum/index.jsx
import React from "react";
import "./Ethereum.css";

function Ethereum(props) {
  const { className } = props;

  return (
    <div className={`ethereum-5 ${className || ""}`}>
      <img className="ethereum-6" src="/img/ethereum@2x.png" alt="Ethereum" />
      <div className="ethereum-7 inter-bold-cape-cod-22px">Ethereum</div>
    </div>
  );
}

export default Ethereum;
