// components/Button210/index.jsx
import React from "react";
import "./Button210.css";

function Button210(props) {
  const { children } = props;

  return (
    <div className="button-2-10">
      <div className="dashboard-10 valign-text-middle raleway-bold-dairy-cream-32px">{children}</div>
    </div>
  );
}

export default Button210;

// alternates/Vue/src/components/Button210.vue
<template>
  <div class="button-2-10">
    <div class="dashboard-9 valign-text-middle raleway-bold-dairy-cream-32px">{{ dashboard }}</div>
  </div>
</template>

<script>
export default {
  name: "Button210",
  props: ["dashboard"],
};
</script>

<style lang="sass">
@import '../../variables'

.button-2-10
  align-items: flex-start
  background-color: $material-themereferrorerror100
  border: 1px none
  border-radius: 16px
  box-shadow: 0px 4px 4px #00000040
  display: flex
  height: 68px
  min-width: 257px
  padding: 14px 31px

.dashboard-9
  height: 38px
  letter-spacing: 0
  line-height: normal
  min-width: 189px
  text-align: center
</style>
