// components/DevEnvironment/index.jsx
import React from "react";
import "./DevEnvironment.css";

function DevEnvironment(props) {
  const { className } = props;

  return (
    <div className={`dev-environment ${className || ""}`}>
      <div className="duckly">
        <div className="duckly-environment valign-text-middle raleway-bold-white-36px">Duckly Environment</div>
        <img className="flying-duck" src="/img/flying-duck@2x.png" alt="Flying Duck" />
      </div>
    </div>
  );
}

export default DevEnvironment;

// alternates/Vue/src/components/DevEnvironment.vue
<template>
  <div :class="[`dev-environment`, className || ``]">
    <div class="duckly">
      <div class="duckly-environment valign-text-middle raleway-bold-white-36px">Duckly Environment</div>
      <img
        class="flying-duck"
        src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/flying-duck@2x.png"
        alt="Flying Duck"
      />
    </div>
  </div>
</template>

<script>
export default {
  name: "DevEnvironment",
  props: ["className"],
};
</script>

<style lang="sass">
.dev-environment
  background-image: url(https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/-livestream@1x.svg)
  background-size: 100% 100%
  display: flex
  height: 720px
  width: 1200px

.duckly
  display: flex
  flex-direction: column
  gap: 32px
  height: 170px
  margin-left: 426px
  margin-top: 266px
  width: 349px

.duckly-environment
  height: 42px
  letter-spacing: 0
  line-height: normal
  text-align: center
  width: 347px

.flying-duck
  height: 96px
  margin-left: 126px
  width: 96px

.dev-environment.dev-environment-1
  background-image: url(https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/-livestream-1@1x.svg)

.dev-environment.dev-environment-2
  background-image: url(https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/-livestream-2@1x.svg)

.dev-environment.dev-environment-3,
.dev-environment.dev-environment-4,
.dev-environment.dev-environment-5,
.dev-environment.dev-environment-6,
.dev-environment.dev-environment-7,
.dev-environment.dev-environment-8,
.dev-environment.dev-environment-9,
.dev-environment.dev-environment-10,
.dev-environment.dev-environment-11
  background-image: url(https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/63448a608ca1456239ecb8bf/img/-livestream@1x.png)
</style>
