// components/Downloads/index.jsx
import React from "react";
import styled from "styled-components";


function Downloads(props) {
  const { className } = props;

  return (
    <Downloads1 className={`downloads-1 ${className || ""}`}>
      <MacClient className="mac-client" src="/img/mac-client-9@2x.png" alt="Mac Client" />
      <MacClient className="windows-client" src="/img/windows-client-9@2x.png" alt="Windows Client" />
      <MacClient className="app-symbol" src="/img/app-symbol-9@2x.png" alt="App Symbol" />
      <MacClient className="playstore" src="/img/playstore-9@2x.png" alt="Playstore" />
      <MacClient className="apple-watch" src="/img/apple-watch-9@2x.png" alt="Apple Watch" />
      <MacClient className="command-line" src="/img/command-line-9@2x.png" alt="Command Line" />
    </Downloads1>
  );
}

const Downloads1 = styled.div`
  margin-top: 60px;
  display: flex;
  align-items: flex-start;
  min-width: 1390px;
  gap: 43px;
  border: 1px none;

  &.downloads-1.downloads-3 {
    align-items: center;
  }

  &.downloads-1.downloads-4 {
    align-items: center;
  }

  &.downloads-1.downloads-5 {
    align-items: center;
  }
`;

const MacClient = styled.img`
  width: 195px;
  height: 99px;
  margin-top: 0;
`;

const MacClient1 = styled.img`
  .downloads-1.downloads-3 & {
    margin-top: unset;
  }
`;

const MacClient2 = styled.img`
  .downloads-1.downloads-4 & {
    margin-top: unset;
  }
`;

const MacClient3 = styled.img`
  .downloads-1.downloads-5 & {
    margin-top: unset;
  }
`;

export default Downloads;

// alternates/Vue/src/components/Downloads.vue
<template>
  <div :class="[`downloads-12`, className || ``]">
    <img
      class="downloads-item"
      src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/mac-client@2x.png"
      alt="Mac Client"
    />
    <img
      class="downloads-item variant-1"
      src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/windows-client@2x.png"
      alt="Windows Client"
    />
    <img
      class="downloads-item variant-2"
      src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/app-symbol@2x.png"
      alt="App Symbol"
    />
    <img
      class="downloads-item variant-3"
      src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/playstore@2x.png"
      alt="Playstore"
    />
    <img
      class="downloads-item variant-4"
      src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/apple-watch@2x.png"
      alt="Apple Watch"
    />
    <img
      class="downloads-item variant-5"
      src="https://anima-uploads.s3.amazonaws.com/projects/62fe76f7359e99eee487b330/releases/634b1e2b9caf1e7ca700d848/img/command-line@2x.png"
      alt="Command Line"
    />
  </div>
</template>

<script>
export default {
  name: "Downloads",
  props: ["className"],
};
</script>

<style lang="sass">
.downloads-12
  align-items: flex-start
  border: 1px none
  display: flex
  gap: 43px
  height: 98.67px
  margin-top: 58.9px
  min-width: 1390px

.downloads-item
  height: 99px
  margin-top: 0
  width: 195px

.downloads-12.downloads-14,
.downloads-12.downloads-19,
.downloads-12.downloads-23
  align-items: center

.downloads-12.downloads-14 .downloads-item,
.downloads-12.downloads-19 .downloads-item,
.downloads-12.downloads-23 .downloads-item
  margin-top: unset

.downloads-12.downloads-14 .downloads-item.variant-1,
.downloads-12.downloads-14 .downloads-item.variant-2,
.downloads-12.downloads-14 .downloads-item.variant-3,
.downloads-12.downloads-14 .downloads-item.variant-4,
.downloads-12.downloads-14 .downloads-item.variant-5,
.downloads-12.downloads-19 .downloads-item.variant-1,
.downloads-12.downloads-19 .downloads-item.variant-2,
.downloads-12.downloads-19 .downloads-item.variant-3,
.downloads-12.downloads-19 .downloads-item.variant-4,
.downloads-12.downloads-19 .downloads-item.variant-5,
.downloads-12.downloads-23 .downloads-item.variant-1,
.downloads-12.downloads-23 .downloads-item.variant-2,
.downloads-12.downloads-23 .downloads-item.variant-3,
.downloads-12.downloads-23 .downloads-item.variant-4,
.downloads-12.downloads-23 .downloads-item.variant-5
  height: 99px
  width: 195px
</style>
