// components/UNIMETA/index.jsx
import React from "react";
import Navbar3 from "../Navbar3";
import Products from "../Products";
import Tools from "../Tools";
import User7 from "../User7";
import DevEnvironment from "../DevEnvironment";
import Footer3 from "../Footer3";
import styled from "styled-components";
import {
  RalewayNormalCapeCod80px,
  RalewayBoldOrchid32px,
  RalewayNormalCapeCod100px,
  RalewayBoldWhite32px,
  RalewayNormalCapeCod26px,
  ValignTextMiddle,
} from "../../../styledMixins";
import "./UNIMETA.css";

function UNIMETA(props) {
  const {
    spanText1,
    spanText2,
    spanText3,
    spanText4,
    logoUniMeta,
    spanText5,
    spanText6,
    spanText7,
    spanText8,
    navbarProps,
    productsProps,
    toolsProps,
    user71Props,
    user72Props,
    user73Props,
    user74Props,
    user75Props,
    user76Props,
    user77Props,
    footer3Props,
  } = props;

  return (
    <div className="container-center-horizontal">
      <div className="uni-meta screen">
        <Body>
          <Navbar3 {...navbarProps} />
          <Hero>
            <FlexCol>
              <UNIMETA1>
                <span className="raleway-normal-cape-cod-80px">{spanText1}</span>
              </UNIMETA1>
              <ThisWeb30Applica>
                <span className="raleway-normal-cape-cod-26px">{spanText2}</span>
              </ThisWeb30Applica>
              <FlexRow>
                <OverlapGroup>
                  <CONTRIBUTE>
                    <span className="raleway-bold-white-32px">{spanText3}</span>
                  </CONTRIBUTE>
                </OverlapGroup>
                <Button2>
                  <DASHBOARD>
                    <span className="raleway-bold-orchid-32px">{spanText4}</span>
                  </DASHBOARD>
                </Button2>
              </FlexRow>
            </FlexCol>
            <LogoUniMeta src={logoUniMeta} alt="logo-uni-meta" />
          </Hero>
          <Products className={productsProps.className} downloadsProps={productsProps.downloadsProps} />
          <Tools className={toolsProps.className} />
          <Team>
            <BecomeAContributor>
              <span className="raleway-normal-cape-cod-100px">{spanText5}</span>
              <Span18>{spanText6}</Span18>
            </BecomeAContributor>
            <OverlapGroup1>
              <Vector src="/img/vector-12@2x.png" alt="Vector" />
              <User7 ellipse2={user71Props.ellipse2} />
              <User7 ellipse2={user72Props.ellipse2} className={user72Props.className} />
              <User7 ellipse2={user73Props.ellipse2} className={user73Props.className} />
              <User7 ellipse2={user74Props.ellipse2} className={user74Props.className} />
              <User7 ellipse2={user75Props.ellipse2} className={user75Props.className} />
              <User7 ellipse2={user76Props.ellipse2} className={user76Props.className} />
              <User7 ellipse2={user77Props.ellipse2} className={user77Props.className} />
            </OverlapGroup1>
          </Team>
          <LiveDeveloping>
            <DevEnvironment />
            <FlexRow1>
              <OverlapGroup2>
                <LEARNHOW>
                  <span>
                    <span className="raleway-bold-white-32px">{spanText7}</span>
                  </span>
                </LEARNHOW>
              </OverlapGroup2>
              <Button21>
                <DASHBOARD1>
                  <span>
                    <span className="raleway-bold-orchid-32px">{spanText8}</span>
                  </span>
                </DASHBOARD1>
              </Button21>
            </FlexRow1>
          </LiveDeveloping>
          <Footer3 className={footer3Props.className} footerMenuProps={footer3Props.footerMenuProps} />
        </Body>
      </div>
    </div>
  );
}

const Body = styled.div`
  width: 1512px;
  height: 5592px;
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  background-color: var(--material-themereferrorerror100);
  border: 1px none;
`;

const Hero = styled.div`
  width: 1512px;
  height: 982px;
  display: flex;
  align-items: center;
  gap: 183px;
  background-color: var(--material-themereferrorerror100);
  overflow: hidden;
  border: 1px none;
`;

const FlexCol = styled.div`
  width: 570px;
  margin-left: 94px;
  margin-bottom: 67px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  min-height: 347px;
`;

const UNIMETA1 = styled.div`
  ${RalewayNormalCapeCod80px}
  min-height: 94px;
  margin-left: 3px;
  letter-spacing: 0;
`;

const ThisWeb30Applica = styled.div`
  ${RalewayNormalCapeCod26px}
  width: 570px;
  min-height: 93px;
  margin-top: 25px;
  letter-spacing: 0;
`;

const FlexRow = styled.div`
  margin-top: 67px;
  margin-left: 3px;
  display: flex;
  align-items: flex-start;
  min-width: 554px;
  gap: 40px;
`;

const OverlapGroup = styled.div`
  height: 68px;
  display: flex;
  padding: 14px 25px;
  justify-content: flex-end;
  align-items: flex-start;
  min-width: 257px;
  background-color: var(--orchid);
  border-radius: 16px;
`;

const CONTRIBUTE = styled.div`
  ${RalewayBoldWhite32px}
  min-height: 38px;
  letter-spacing: 0;
`;

const DASHBOARD = styled.div`
  ${RalewayBoldOrchid32px}
  min-height: 38px;
  letter-spacing: 0;
`;

const Button2 = styled.div`
  height: 68px;
  display: flex;
  padding: 14px 26px;
  align-items: flex-start;
  min-width: 257px;
  background-color: var(--material-themereferrorerror100);
  border-radius: 16px;
  border: 1px none;
  box-shadow: 0px 4px 4px #00000040;
`;

const LogoUniMeta = styled.img`
  width: 1000px;
  height: 1000px;
  align-self: flex-end;
  margin-bottom: -18px;
  object-fit: cover;
`;

const Team = styled.div`
  width: 1512px;
  height: 982px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 61px;
  background-color: var(--material-themereferrorerror100);
  border: 1px none;
`;

const BecomeAContributor = styled.div`
  ${RalewayNormalCapeCod100px}
  min-height: 117px;
  margin-top: 104px;
  min-width: 1006px;
  letter-spacing: 0;
`;

const Span18 = styled.span`
  font-family: var(--font-family-raleway);
  font-weight: 400;
  color: var(--orchid);
  font-size: 100px;
`;

const OverlapGroup1 = styled.div`
  width: 1512px;
  height: 700px;
  position: relative;
`;

const Vector = styled.img`
  position: absolute;
  width: 1512px;
  height: 500px;
  top: 200px;
  left: 0;
`;

const LiveDeveloping = styled.div`
  width: 1512px;
  height: 982px;
  position: relative;
  display: flex;
  flex-direction: column;
  padding: 40px 0;
  align-items: center;
  gap: 66px;
  background-color: var(--material-themereferrorerror100);
  border: 1px none;
`;

const FlexRow1 = styled.div`
  display: flex;
  align-items: flex-start;
  min-width: 614px;
  gap: 100px;
`;

const OverlapGroup2 = styled.div`
  height: 68px;
  display: flex;
  padding: 14px 26px;
  align-items: flex-start;
  min-width: 257px;
  background-color: var(--orchid);
  border-radius: 16px;
`;

const LEARNHOW = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldWhite32px}
            height: 38px;
  min-width: 194px;
  text-align: center;
  letter-spacing: 0;
`;

const Button21 = styled.div`
  height: 68px;
  display: flex;
  padding: 14px 31px;
  align-items: flex-start;
  min-width: 257px;
  background-color: var(--material-themereferrorerror100);
  border-radius: 16px;
  border: 1px none;
  box-shadow: 0px 4px 4px #00000040;
`;

const DASHBOARD1 = styled.div`
  ${ValignTextMiddle}
  ${RalewayBoldOrchid32px}
            height: 38px;
  min-width: 189px;
  text-align: center;
  letter-spacing: 0;
`;

export default UNIMETA;

// alternates/Vue/src/components/UNIMETA.vue
<template>
  <div class="uni-meta screen">
    <div class="uni-meta-1">
      <div class="body-32">
        <navbar7
          :className="navbar7Props.className"
          :buttonLoginProps="navbar7Props.buttonLoginProps"
          :buttonWalletProps="navbar7Props.buttonWalletProps"
        />
        <div class="hero-28">
          <div class="flex-col-20">
            <div class="uni-meta-2 raleway-normal-cape-cod-80px">{{ uniMeta }}</div>
            <p class="this-web-30-applica-10 raleway-normal-cape-cod-26px">{{ thisWeb30Applica }}</p>
            <div class="flex-row-105">
              <div class="overlap-group-101">
                <div class="contribute-10 raleway-bold-white-32px">{{ contribute }}</div>
              </div>
              <button221 :dashboard="button221Props.dashboard" />
            </div>
          </div>
          <img class="logo-uni-meta-2" :src="logoUniMeta" alt="logo-uni-meta" />
        </div>
        <products :className="productsProps.className" :downloadsProps="productsProps.downloadsProps" />
        <tools
          :className="toolsProps.className"
          :packages1Props="toolsProps.packages1Props"
          :packages2Props="toolsProps.packages2Props"
          :packages3Props="toolsProps.packages3Props"
        />
        <div class="team-10">
          <div class="become-a-contributor-10 raleway-normal-white-100px">
            <span class="raleway-normal-cape-cod-100px">{{ spanText1 }}</span
            ><span class="span1-16">{{ spanText2 }}</span>
          </div>
          <avatars
            :user71Props="avatarsProps.user71Props"
            :user72Props="avatarsProps.user72Props"
            :user73Props="avatarsProps.user73Props"
            :user74Props="avatarsProps.user74Props"
            :user75Props="avatarsProps.user75Props"
            :user76Props="avatarsProps.user76Props"
            :user77Props="avatarsProps.user77Props"
          />
        </div>
        <div class="live-developing-10">
          <dev-environment :className="devEnvironmentProps.className" />
          <div class="flex-row-106">
            <div class="overlap-group-102">
              <div class="learn-how-10 valign-text-middle raleway-bold-white-32px">{{ learnHow }}</div>
            </div>
            <button222 :dashboard="button222Props.dashboard" />
          </div>
        </div>
        <x-footer11 :className="xFooter11Props.className" :footerMenu2Props="xFooter11Props.footerMenu2Props" />
      </div>
    </div>
  </div>
</template>

<script>
import Navbar7 from "./Navbar7";
import Button221 from "./Button221";
import Products from "./Products";
import Tools from "./Tools";
import Avatars from "./Avatars";
import DevEnvironment from "./DevEnvironment";
import Button222 from "./Button222";
import xFooter11 from "./xFooter11";
export default {
  name: "UNIMETA",
  components: {
    Navbar7,
    Button221,
    Products,
    Tools,
    Avatars,
    DevEnvironment,
    Button222,
    xFooter11,
  },
  props: [
    "uniMeta",
    "thisWeb30Applica",
    "contribute",
    "logoUniMeta",
    "spanText1",
    "spanText2",
    "learnHow",
    "navbar7Props",
    "button221Props",
    "productsProps",
    "toolsProps",
    "avatarsProps",
    "devEnvironmentProps",
    "button222Props",
    "xFooter11Props",
  ],
};
</script>

<style lang="sass">
@import '../../variables'

.uni-meta
  align-items: center
  border: 1px none
  display: flex
  flex-direction: column
  gap: 50px
  height: 100vh
  min-height: 5592px
  min-width: 1512px
  width: 100%

.uni-meta-1
  display: flex
  height: 5592px
  min-width: 1512px

.body-32
  background-color: $material-themereferrorerror100
  border: 1px none
  display: flex
  flex-direction: column
  height: 5592px
  position: relative
  width: 1512px

.hero-28
  align-items: center
  background-color: $material-themereferrorerror100
  border: 1px none
  display: flex
  gap: 183px
  width: 1512px

.flex-col-20
  align-items: flex-start
  display: flex
  flex-direction: column
  margin-bottom: 67.0px
  margin-left: 94px
  min-height: 347px
  width: 570px

.uni-meta-2
  letter-spacing: 0
  line-height: normal
  margin-left: 3px
  min-height: 94px

.this-web-30-applica-10
  letter-spacing: 0
  line-height: normal
  margin-top: 25px
  width: 570px

.flex-row-105
  align-items: flex-start
  display: flex
  gap: 40px
  margin-left: 3px
  margin-top: 67px
  min-width: 554px
  position: relative

.overlap-group-101
  align-items: center
  background-color: $orchid
  border-radius: 16px
  display: flex
  height: 68px
  justify-content: flex-end
  min-width: 257px
  padding: 0 25px

.contribute-10
  letter-spacing: 0
  line-height: normal
  min-height: 38px
  min-width: 206px

.logo-uni-meta-2
  height: 982px
  object-fit: cover
  width: 665px

.team-10
  background-color: $material-themereferrorerror100
  border: 1px none
  display: flex
  flex-direction: column
  gap: 60px
  height: 982px
  position: relative

.become-a-contributor-10
  height: 117px
  letter-spacing: 0
  line-height: normal
  margin-left: 253px
  margin-top: 105px
  width: 1006px

.span1-16
  color: $orchid
  font-family: $font-family-raleway
  font-size: $font-size-xxxl
  font-weight: 400

.live-developing-10
  align-items: center
  background-color: $material-themereferrorerror100
  border: 1px none
  display: flex
  flex-direction: column
  gap: 66px
  height: 982px
  padding: 40px 0
  position: relative

.flex-row-106
  align-items: flex-start
  display: flex
  gap: 100px
  min-width: 614px
  position: relative

.overlap-group-102
  align-items: center
  background-color: $orchid
  border-radius: 16px
  display: flex
  height: 68px
  min-width: 257px
  padding: 0 26px

.learn-how-10
  height: 38px
  letter-spacing: 0
  line-height: normal
  min-width: 194px
  text-align: center
</style>
