// alternates/Vue/src/components/FooterMenu2.vue
<template>
  <div class="footer-menu-16">
    <img class="x3-rupt-logo-1" :src="x3RuptLogo1" alt="3RUPT Logo 1" />
    <div class="flex-row-71 raleway-bold-cape-cod-20px">
      <div class="hire-me-48">HIRE ME</div>
      <div class="github-35">GITHUB</div>
      <div class="open-source-47">OPEN-SOURCE</div>
      <div class="organizations-37">ORGANIZATIONS</div>
      <img class="button-25" :src="button1" alt="button" /><img class="button-30" :src="button2" alt="button" />
    </div>
  </div>
</template>

<script>
export default {
  name: "FooterMenu2",
  props: ["x3RuptLogo1", "button1", "button2"],
};
</script>

<style lang="sass">
.footer-menu-16,
.footer-menu-17,
.footer-menu-18,
.footer-menu-19,
.footer-menu-20,
.footer-menu-21,
.footer-menu-22,
.footer-menu-23,
.footer-menu-24,
.footer-menu-25,
.footer-menu-26
  align-items: center
  display: flex
  flex-direction: column
  gap: 53px
  min-height: 233px
  width: 1391px

.x3-rupt-logo-1,
.logo-bitcell-1,
.cec-logo-14,
.logo-cheers-1,
.logo-half-and-half-1,
.logo-the-public-1,
.logo-knott-bank-1,
.logo-hooden-1,
.logo-blockify-1,
.logo-uni-meta-1,
.tradent-logo5-transparent-2-12
  height: 120px
  margin-right: 66.85px
  object-fit: cover
  width: 120px

.flex-row-71,
.flex-row-72,
.flex-row-73,
.flex-row-74,
.flex-row-75,
.flex-row-76,
.flex-row-77,
.flex-row-78,
.flex-row-79,
.flex-row-80,
.flex-row-81
  align-items: center
  display: flex
  margin-right: 8.0px
  min-width: 1383px

.hire-me-48,
.hire-me-49,
.hire-me-50,
.hire-me-51,
.hire-me-52,
.hire-me-53,
.hire-me-54,
.hire-me-55,
.hire-me-56,
.hire-me-57,
.hire-me-58
  letter-spacing: 0
  line-height: normal
  margin-top: 1.0px
  text-align: center
  width: 124px

.github-35,
.github-36,
.github-37,
.github-38,
.github-39,
.github-40,
.github-41,
.github-42,
.github-43,
.github-44,
.github-45
  letter-spacing: 0
  line-height: normal
  margin-left: 30px
  margin-top: 1.0px
  text-align: center
  width: 118px

.open-source-47,
.open-source-48,
.open-source-49,
.open-source-50,
.open-source-51,
.open-source-52,
.open-source-53,
.open-source-54,
.open-source-55,
.open-source-56,
.open-source-57
  letter-spacing: 0
  line-height: normal
  margin-bottom: 1.0px
  margin-left: 28px
  text-align: center
  width: 223px

.organizations-37,
.organizations-38,
.organizations-39,
.organizations-40,
.organizations-41,
.organizations-42,
.organizations-43,
.organizations-44,
.organizations-45,
.organizations-46,
.organizations-47
  letter-spacing: 0
  line-height: normal
  margin-left: 29px
  margin-top: 1.0px
  text-align: center
  width: 250px

.button-25,
.button-33,
.button-35,
.button-37,
.button-39,
.button-41,
.button-43,
.button-45,
.button-47,
.button-49,
.button-51
  height: 60px
  margin-left: 76px
  width: 215px

.button-30,
.button-34,
.button-36,
.button-38,
.button-40,
.button-42,
.button-44,
.button-46,
.button-48,
.button-50,
.button-52
  height: 60px
  margin-left: 75px
  width: 215px
</style>

// components/FooterMenu2/index.jsx
import React from "react";
import XButton from "../XButton";
import "./FooterMenu2.css";

function FooterMenu2(props) {
  const { xButton1Props, xButton2Props } = props;

  return (
    <div className="footer-menu-7">
      <img className="cec-logo-6" src="/img/-cec-logo@2x.png" alt="cec-logo" />
      <div className="flex-row-18">
        <div className="links-4 raleway-bold-cape-cod-20px">
          <div className="hire-me-23">HIRE ME</div>
          <div className="github-11">GITHUB</div>
          <div className="open-source-15">OPEN-SOURCE</div>
          <div className="organizations-11">ORGANIZATIONS</div>
        </div>
        <XButton className={xButton1Props.className}>{xButton1Props.children}</XButton>
        <XButton className={xButton2Props.className}>{xButton2Props.children}</XButton>
      </div>
    </div>
  );
}

export default FooterMenu2;
