// alternates/Vue/src/components/Button2.vue
<template>
  <div class="button-2-1">
    <div class="dashboard raleway-bold-mexican-red-32px">{{ dashboard }}</div>
  </div>
</template>

<script>
export default {
  name: "Button2",
  props: ["dashboard"],
};
</script>

<style lang="sass">
@import '../../variables'

.button-2-1
  align-items: flex-start
  background-color: $material-themereferrorerror100
  border: 1px none
  border-radius: 16px
  box-shadow: 0px 4px 4px #00000040
  display: flex
  height: 68px
  min-width: 257px
  padding: 14px 26px

.dashboard
  letter-spacing: 0
  line-height: normal
  min-height: 38px
</style>

// components/Button2/index.jsx
import React from "react";
import styled from "styled-components";
import { RalewayBoldMexicanRed32px } from "../../styledMixins";


function Button2(props) {
  const { children } = props;

  return (
    <Button21>
      <DASHBOARD>
        <span className="raleway-bold-mexican-red-32px">{children}</span>
      </DASHBOARD>
    </Button21>
  );
}

const Button21 = styled.div`
  height: 68px;
  display: flex;
  padding: 14px 26px;
  align-items: flex-start;
  min-width: 257px;
  background-color: var(--material-themereferrorerror100);
  border-radius: 16px;
  border: 1px none;
  box-shadow: 0px 4px 4px #00000040;
`;

const DASHBOARD = styled.div`
  ${RalewayBoldMexicanRed32px}
  min-height: 38px;
  letter-spacing: 0;
`;

export default Button2;
