// alternates/Vue/src/components/ButtonSignup.vue
<template>
  <div :class="[`button-signup-1`, className || ``]">
    <div class="overlap-group2-2">
      <div class="sign-up-1 valign-text-middle raleway-normal-cape-cod-22px">Sign-Up</div>
    </div>
  </div>
</template>

<script>
export default {
  name: "ButtonSignup",
  props: ["className"],
};
</script>

<style lang="sass">
@import '../../variables'

.button-signup-1,
.button-signup-1.button-signup
  align-items: flex-start
  display: flex
  margin-left: 27px
  min-width: 157px

.overlap-group2-2
  align-items: flex-start
  background-color: $alto
  border: 1px solid
  border-color: $cape-cod
  border-radius: 8px
  display: flex
  height: 43px
  min-width: 155px
  padding: 8px 35px

.sign-up-1
  height: 26px
  letter-spacing: 0
  line-height: normal
  min-width: 84px
  text-align: center

.button-signup-1.button-signup-2,
.button-signup-1.button-signup-4,
.button-signup-1.button-signup-5
  align-items: unset
  display: unset
  height: 43px
  margin-left: unset
</style>

// components/ButtonSignup/index.jsx
import React from "react";
import "./ButtonSignup.css";

function ButtonSignup(props) {
  const { className } = props;

  return (
    <div className={`button-signup-1 ${className || ""}`}>
      <div className="overlap-group2-2">
        <div className="sign-up-1 valign-text-middle raleway-normal-cape-cod-22px">Sign-Up</div>
      </div>
    </div>
  );
}

export default ButtonSignup;
